services:
  pudl_viewer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pudl-viewer
    environment:
      PUDL_VIEWER_SECRET_KEY: ${PUDL_VIEWER_FLASK_SECRET_KEY-superset}
      FLASK_RUN_PORT: 5000
    ports:
      - target: 5000
        published: 8081