services:
  pudl_viewer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pudl-viewer
    environment:
      PUDL_VIEWER_SECRET_KEY: ${PUDL_VIEWER_FLASK_SECRET_KEY-superset}
      PORT: 8080
    ports:
      - target: 8080
        published: 8081