volumes:
  pudl_viewer_postgres_data:
services:
  eel_hole:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: eel-hole
    environment:
      PUDL_VIEWER_SECRET_KEY: ${PUDL_VIEWER_FLASK_SECRET_KEY-pudl_viewer_secret}
      PUDL_VIEWER_DB_HOST: ${PUDL_VIEWER_DB_HOST-postgres}
      PUDL_VIEWER_DB_PORT: ${PUDL_VIEWER_DB_PORT-5432}
      PUDL_VIEWER_DB_USERNAME: ${PUDL_VIEWER_DB_USERNAME-pudl_viewer}
      PUDL_VIEWER_DB_PASSWORD: ${PUDL_VIEWER_DB_PASSWORD-pudl_viewer}
      PUDL_VIEWER_DB_NAME: ${PUDL_VIEWER_DB_NAME-pudl_viewer}
      PUDL_VIEWER_AUTH0_DOMAIN: ${PUDL_VIEWER_AUTH0_DOMAIN}
      PUDL_VIEWER_AUTH0_CLIENT_ID: ${PUDL_VIEWER_AUTH0_CLIENT_ID}
      PUDL_VIEWER_AUTH0_CLIENT_SECRET: ${PUDL_VIEWER_AUTH0_CLIENT_SECRET}
      PUDL_VIEWER_LOGIN_DISABLED: ${PUDL_VIEWER_LOGIN_DISABLED}
      FLASK_APP: ${FLASK_APP}
      GRACEFUL_TIMEOUT: 1
      PORT: 8080
    volumes:
      - type: bind
        source: eel_hole
        target: /app/eel_hole
        bind:
          selinux: z
      - type: bind
        source: dist
        target: /app/dist
        bind:
          selinux: z
    ports:
      - target: 8080
        published: 8080
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: pudl_viewer
      POSTGRES_USER: pudl_viewer
      POSTGRES_PASSWORD: pudl_viewer
    volumes:
      - pudl_viewer_postgres_data:/var/lib/postgresql/data
    ports:
      - target: 5432
        published: 5432
