---
services:
  eel_hole:
    environment:
      PUDL_VIEWER_INTEGRATION_TEST: true
    command: >
      sh -c "
        uv run flask --app eel_hole db upgrade &&
        uv run --no-dev flask --app eel_hole run --host 0.0.0.0 --port 8080 --reload
      "
  postgres:
    volumes: !reset []
