[project]
name = "parquet-fe-prototype"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "flask>=3.1.0",
    "frictionless>=5.18.0",
    "pyyaml>=6.0.2",
    "whoosh>=2.7.4",
]
