"""add email verification flag

Revision ID: 0203498a6957
Revises: 745f26f7b81f
Create Date: 2026-03-19 16:31:01.640622

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0203498a6957"
down_revision = "745f26f7b81f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "email_verified",
                sa.Boolean(),
                server_default=sa.text("false"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("email_verified")

    # ### end Alembic commands ###
