"""Add privacy settings to User.

Revision ID: 745f26f7b81f
Revises: 0309db1e86c0
Create Date: 2025-08-28 15:59:11.829604

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '745f26f7b81f'
down_revision = '0309db1e86c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('accepted_privacy_policy', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('do_individual_outreach', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('send_newsletter', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('send_newsletter')
        batch_op.drop_column('do_individual_outreach')
        batch_op.drop_column('accepted_privacy_policy')

    # ### end Alembic commands ###
