---
name: build-deploy-staging
on:
  workflow_dispatch:

jobs:
  build_deploy_staging:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Noop
        run: echo "Stub workflow"
